<?php
// Start output buffering to catch any unwanted output (like warnings)
ob_start();

session_start();

// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    // Clean any previous output
    ob_clean();
    $response = array(
        'success' => false,
        'message' => 'You are not logged in. Please log in again.'
    );
    header('Content-Type: application/json');
    echo json_encode($response);
    exit();
}

// Include database configuration
require_once 'config.php';

// Get user ID from session
 $user_id = $_SESSION['user_id'];

// Initialize response array
 $response = array(
    'success' => false,
    'message' => 'An unknown error occurred.'
);

// Check if form was submitted
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get form data
    $current_password = $_POST['current_password'] ?? '';
    $new_password = $_POST['new_password'] ?? '';
    $confirm_password = $_POST['confirm_password'] ?? '';
    
    // Validate inputs
    if (empty($current_password) || empty($new_password) || empty($confirm_password)) {
        $response['message'] = 'All fields are required.';
    } elseif ($new_password !== $confirm_password) {
        $response['message'] = 'New password and confirm password do not match.';
    } elseif (strlen($new_password) < 6) {
        $response['message'] = 'Password must be at least 6 characters long.';
    } else {
        // Get current password hash from database
        $stmt = $conn->prepare("SELECT password FROM users WHERE id = ?");
        if ($stmt) {
            $stmt->bind_param("i", $user_id);
            $stmt->execute();
            $result = $stmt->get_result();
            
            if ($result->num_rows > 0) {
                $user_data = $result->fetch_assoc();
                
                // Verify current password
                if (password_verify($current_password, $user_data['password'])) {
                    // Hash new password
                    $new_password_hash = password_hash($new_password, PASSWORD_DEFAULT);
                    
                    // Update password in database
                    $update_stmt = $conn->prepare("UPDATE users SET password = ?, updated_at = NOW() WHERE id = ?");
                    if ($update_stmt) {
                        $update_stmt->bind_param("si", $new_password_hash, $user_id);
                        
                        if ($update_stmt->execute()) {
                            $response['success'] = true;
                            $response['message'] = 'Password changed successfully!';
                            
                            // Log the password change (optional)
                            $log_stmt = $conn->prepare("INSERT INTO user_activity_logs (user_id, activity, details, created_at) VALUES (?, 'Password Change', 'Password changed successfully', NOW())");
                            if ($log_stmt) {
                                $log_stmt->bind_param("i", $user_id);
                                $log_stmt->execute();
                            }
                        } else {
                            $response['message'] = 'Failed to update password in database.';
                        }
                    } else {
                        $response['message'] = 'Database error: Could not prepare update statement.';
                    }
                } else {
                    $response['message'] = 'Current password is incorrect.';
                }
            } else {
                $response['message'] = 'User not found.';
            }
            $stmt->close();
        } else {
            $response['message'] = 'Database error: Could not prepare select statement.';
        }
    }
} else {
    // Not a POST request
    $response['message'] = 'Invalid request method.';
}

// Clean any output buffer content generated by warnings/errors
ob_clean();

// Return JSON response
header('Content-Type: application/json');
echo json_encode($response);
?>